name: nanoclip
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - faiss-cpu
  - pip
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
    - lightning==2.4.0
    - kaggle==1.6.17
    - transformers==4.46.3
    - tensorboard==2.18.0
    - gradio==5.6.0
    - xformers==0.0.28.post3